### ISSUE TITLE
Mattermost: Error on sending

### ISSUE THREAD

**Issue by bafplus** [infojunkie/MantisBT-Slack#40] opened 2017-11-07 14:25 UTC
The error:
APPLICATION ERROR #plugin_Slack_ERROR_CURL
The request to Slack didn’t go through. Check your webhook URL. Also make sure there are no unusual characters in your bot name or bot icon settings. Further details may be printed below this box.
Please use the “Back” button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

I cant seem to find something wrong else then a empty UID in the string.
There was a commit 6 days ago in the 1.2 branch that fixes a simular issue.
![90406927fd6e022af2d7d900b1d2e67c5d86bf8d](https://user-images.githubusercontent.com/6432986/32498372-d7ef3ca2-c3cf-11e7-85b1-b466ec417e44.jpg)

**Comment by bafplus** [comment] 2017-11-07 14:27
If i replace the webhook with a slack webhook everything works fine.
So there is something of in the mattermost code in this plugin or at mattermost code.

I myself are no coder so have no clue where to look for a fix.

**Comment by infojunkie** [comment] 2017-11-07 15:41
Strange, it's the same commit that went into both branches. @secustor would you mind validating that the latest `master` works with Mattermost for you?

**Comment by bafplus** [comment] 2017-11-07 15:43
Only the 1.2 branch was merged

**Comment by infojunkie** [comment] 2017-11-07 15:45
Here's the commit on master: https://github.com/infojunkie/MantisBT-Slack/commit/8aa67a830ca791936c05eede149d240d95579bcb - or is there another one I missed?

**Comment by bafplus** [comment] 2017-11-07 15:47
Probably because the slack.php in main branch was last updated 2 months ago?

Not saying its the root of my issue, but looks related.

**Comment by infojunkie** [comment] 2017-11-07 15:51
The commit I point to above was made 6 days ago on master. Please make sure you are pulling the latest code, and from the correct repo: https://github.com/infojunkie/MantisBT-Slack or https://github.com/mantisbt-plugins/Slack

**Comment by bafplus** [comment] 2017-11-07 15:55
![naamloos](https://user-images.githubusercontent.com/6432986/32502972-6210f464-c3dc-11e7-9578-00f74637f9a0.png)
So...why is it 2 months there? Or am i missing something?

**Comment by infojunkie** [comment] 2017-11-07 15:58
I see.. the patch was submitted two months ago. I merged the PR 6 days ago.

**Comment by bafplus** [comment] 2017-11-07 16:05
So that should be ok then?

**Comment by infojunkie** [comment] 2017-11-07 16:13
Yes, the patch is in there. I doubt I will have time to test Mattermost myself, so I hope @secustor can confirm.

**Comment by bafplus** [comment] 2017-11-07 16:33
I wil test the master

**Comment by bafplus** [comment] 2017-11-07 16:42
I just tested current master and stil get that error.

**Comment by secustor** [comment] 2017-11-07 18:24
@bafplus try to add the following line to Slack.php at line 268 (1.2.x branch) right before the post fields. 
```php
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
```


It then should look like this: 
``` php
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);
        $result = curl_exec($ch);
        if ($result !== 'ok') {
            trigger_error(curl_errno($ch) . ': ' . curl_error($ch), E_USER_WARNING);
            plugin_error('ERROR_CURL', E_USER_ERROR);
        }
        curl_close($ch);
```

This will tell mattermost how to exactly handle the request, this shouldn't be necessary, but its worth a try.

**Comment by bafplus** [comment] 2017-11-07 18:27
but i use mantis 2.x?

**Comment by secustor** [comment] 2017-11-09 11:54
For 2.x that would be line 295. 

```php
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);
```

**Comment by bafplus** [comment] 2017-11-09 13:57
confirmed, @secustor that worked

**Comment by infojunkie** [comment] 2017-11-09 17:04
Sorry, I closed too soon - I will add the relevant lines to both branches.

**Comment by dimitriacosta** [comment] 2017-11-14 18:00
I can't make it work on mattermost, I may configured mantis wrong, I don't know but I need some help here, can you guys give me a hand?

Here's my current settings, oh by the way the webhook url is not for slack it is for my private mattermost 

![screen shot 2017-11-14 at 10 56 49 am](https://user-images.githubusercontent.com/5995547/32796111-f954f20a-c92a-11e7-8661-cc3a0e2bae08.png)

**Comment by secustor** [comment] 2017-11-14 19:45
@dimitriacosta 
Your default channel is not valid. 
For mattermost you  have to use the channel name as provided in the URL and without the hashtag
e.g. 'town-square' for the Vanilla default channel

**Comment by dimitriacosta** [comment] 2017-11-14 20:01
Hi @secustor thanks for your quick answer.

I did what you said and here's my new settings
<img width="1495" alt="screen shot 2017-11-14 at 12 58 14 pm" src="https://user-images.githubusercontent.com/5995547/32801901-a82e22fa-c93b-11e7-9eb2-12bf6981f2d3.png">

It's still not working because every time I create a new issue I got this error
```
APPLICATION ERROR #plugin_Slack_ERROR_CURL

The request to Slack didn't go through. Check your webhook URL. Also make sure there are no unusual characters in your bot name or bot icon settings. Further details may be printed below this box.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

**Comment by secustor** [comment] 2017-11-14 20:06
@dimitriacosta You forget to mask the webhook on your second screenshot. 

Activate the debug mode for webhooks in Mattermost and check what it is receiving?

**Comment by dimitriacosta** [comment] 2017-11-14 20:12
I got something like this
`[2017/11/14 20:09:33 UTC] [EROR] /hooks/<key>:IncomingWebhookRequestFromJson code=400 rid=3gjnzmnrxb8qfkof7p5ncae36o uid= ip=187.189.17.225 Unable to parse incoming data [details: EOF]`

**Comment by dimitriacosta** [comment] 2017-11-14 22:06
Hey @secustor I found this in my mattermost instance

![screen shot 2017-11-14 at 3 03 15 pm](https://user-images.githubusercontent.com/5995547/32807475-2fa348d0-c94d-11e7-94ba-8bbb298a4f18.png)

I guess that's from you 😅 but I just can't make it work 😔

**Comment by dimitriacosta** [comment] 2017-11-14 22:17
I am running mantis from a docker image so maybe there is something wrong with it, to be hones I have no idea.

It works perfectly fine with slack but not in mattermost.

By the way, notifications are sent only if the issue is created as public, if I make an issue as private I don't get anythinng

**Comment by secustor** [comment] 2017-11-14 22:42
Do you have added the line above to the plugin? 
If yes, please share the ticket which you try to open, so I can try to reproduce on my local system.

**Comment by dimitriacosta** [comment] 2017-11-14 22:56
Oh I didn't noticed that line was removed when I recreated the docker image, I've just aded that line and its working fine now.

But now I have another question, what if I want mantis to send notifications even if issues are private? Considering that I have a private channel for the development team

**Comment by secustor** [comment] 2017-11-14 23:25
In that case you have to modify the source code. Line 266 of Slack.php is a hot hint  ;) . This will ignore the privacy setting of all issues and notes. BE WARNED!

On the mattermost side you need to create a webhook specific to the private channel and then let the plugin write on it too.

**Comment by dimitriacosta** [comment] 2017-11-15 00:01
Great it worked, thank you very much for your help 👍

**Comment by infojunkie** [comment] 2017-11-15 06:02
Thanks everyone. Will update the branches when I'm back at a computer one week from now.

**Closed** 2018-02-06 21:52 UTC
